language: generic
sudo: required
services:
	- docker
	
before_install:
	- docker build -t natedog/myrepo -f Dockerfile.dev .
	
script:
	- docker run -e CI=true natedog/myrepo npm run test -- --coverage
	
